title: Ahlu-Sunnah Al Islam
email: falisznalt@gmail.com
description: >-
  Spreading the truth. Authentic Islamic knowledge based on Quran and Sunnah.
baseurl: "/Al-Sunnah-Al-Islam-Theme"
url: "https://fali17.github.io"
theme: minima
plugins:
  - jekyll-feed
markdown: kramdown

# Logo
logo: /assets/images/logo.png
logo_width: 96px
